---
#Install and configure the AWS console
- name: 'Install PIP'
  become: true
  become_method: sudo
  apt:
    name: python-pip
    state: present
- name: 'Check and register if awscli installed'
  become: true
  become_method: sudo
  shell: pip list | grep aws | wc -l
  register: awscli_installed
- name: 'Install AWS Console if not already installed'
  become: true
  become_method: sudo
  shell: pip install awscli --ignore-installed six
  when: awscli_installed.stdout == "0"
- name: 'Update AWS Console if already installed'
  become: true
  become_method: sudo
  shell: pip install --upgrade awscli
  when: awscli_installed.stdout == "1"
