---
#Set the default inventory. This will just consist of the primary management host to start with
- name: 'Confirm /etc/ansible directory exists'
  become: true
  become_method: sudo
  file:
    path: "/etc/ansible"
    state: directory
- name: 'Set the management host in the default inventory file'
  become: true
  become_method: sudo
  template:
    backup: yes
    force: yes
    mode: 0644
    dest: '/etc/ansible/hosts'
    src: 'hosts.j2'
