---
#Insert a .sh file into the bastion host to easily ssh to the management server
- name: 'Adding .sh File to Admin dir to SSH Into Management Server'
  template:
    dest: /home/admin/gotomanagement.sh
    force: yes
    mode: 0744
    src: gotomanagement.sh.j2
