---
#This playbook governs the configuration of the management server once it has been spun up. Run the standard common role and custom configuration in the management role
- hosts: management
  roles:
    - common
    - management
