---
#Will begin the process of bringing up the minimum components in AWS. Once minimum components are completed, the management server will take over for the rest of the configuration
- include: spoolvpc.yml
- include: spoolsg.yml
- include: spoolkeypair.yml
- include: spoolec2.yml
- include: addinventory.yml
- include: verifyssh.yml
