---
#Create Key Pairs for access to vpc
- name: 'Confirm keypair directory exists'
  file:
    path: "{{ playbook_dir }}/keypairs"
    state: directory
- name: 'Creating Key Pairs for {{ ec2_cfg.keypair_1.name }}'
  ansible-ssh-keygen.sh:
    comment: "{{ ec2_cfg.keypair_1.name }}"
- name: 'Uploading Key Pairs for {{ ec2_cfg.keypair_1.name }} to AWS'
  ec2_key:
    region: "{{ ec2_cfg.region }}"
    name: "{{ ec2_cfg.keypair_1.name }}"
    key_material: "{{ item }}"
  with_file: "{{ playbook_dir }}/keypairs/{{ ec2_cfg.keypair_1.name }}.pub"
  register: keypair_1
- name: 'Creating Key Pairs for {{ ec2_cfg.keypair_2.name }}'
  ansible-ssh-keygen.sh:
    comment: "{{ ec2_cfg.keypair_2.name }}"
- name: 'Uploading Key Pairs for {{ ec2_cfg.keypair_2.name }} to AWS'
  ec2_key:
    region: "{{ ec2_cfg.region }}"
    name: "{{ ec2_cfg.keypair_2.name }}"
    key_material: "{{ item }}"
  with_file: "{{ playbook_dir }}/keypairs/{{ ec2_cfg.keypair_2.name }}.pub"
  register: keypair_2
