---
#Create Key Pairs for access to vpc
- name: 'Creating Key Pairs for {{ ec2_cfg.keypair_1.name }}'
  ec2_key:
    region: "{{ ec2_cfg.region }}"
    name: "{{ ec2_cfg.keypair_1.name }}"
  register: keypair_1
- name: 'Saving Private Key for {{ ec2_cfg.keypair_1.name }}'
  copy:
    content: "{{ keypair_1.key.private_key }}"
    dest: "groundzero/keypairs/{{ ec2_cfg.keypair_1.name }}"
  when: keypair_1.changed == true
- name: 'Creating Key Pairs for {{ ec2_cfg.keypair_2.name }}'
  ec2_key:
    region: "{{ ec2_cfg.region }}"
    name: "{{ ec2_cfg.keypair_2.name }}"
  register: keypair_2
- name: 'Saving Private Key for {{ ec2_cfg.keypair_2.name }}'
  copy:
    content: "{{ keypair_2.key.private_key }}"
    dest: "groundzero/keypairs/{{ ec2_cfg.keypair_2.name }}"
  when: keypair_2.changed == true

#NOTE: May need to change copy to fetch as jey needs to be stored on the local machine, not the remove machine. Not an issue however if local machine and remote machine are actually the same
