---
#Create Key Pairs for access to vpc
- name: 'Confirm keypair directory exists'
  file:
    path: "{{ playbook_dir }}/keypairs"
    state: directory
- name: 'Creating Key Pairs for {{ ec2_cfg.keypair_1.name }}'
  ec2_key:
    region: "{{ ec2_cfg.region }}"
    name: "{{ ec2_cfg.keypair_1.name }}"
  register: keypair_1
- name: 'Saving Private Key for {{ ec2_cfg.keypair_1.name }}'
  copy: 
    content: "{{ keypair_1.key.private_key }}"
    dest: "keypairs/{{ ec2_cfg.keypair_1.name }}.pem"
    mode: 0600
#  delegate_to: 127.0.0.1
  when: keypair_1.changed == true
- name: 'Creating Key Pairs for {{ ec2_cfg.keypair_2.name }}'
  ec2_key:
    region: "{{ ec2_cfg.region }}"
    name: "{{ ec2_cfg.keypair_2.name }}"
  register: keypair_2
- name: 'Saving Private Key for {{ ec2_cfg.keypair_2.name }}'
  copy:
    content: "{{ keypair_2.key.private_key }}"
    dest: "keypairs/{{ ec2_cfg.keypair_2.name }}.pem"
    mode: 0600
#  delegate_to: 127.0.0.1
  when: keypair_2.changed == true

#Delegate commands no longer required as we are forcing the all playbooks for ground zero to be local
