---
#Basic configuration items for the aws playbooks
vpc_cfg:
  region: ap-southeast-2
  tags: {"Name":"coffeemate.network.vpc"}
  cidr: 10.0.0.0/16
  subnet_1:
    cidr: 10.0.16.0/20
    az: ap-southeast-2a
    tags: {"Name":"coffeemate.network.subnet.admin.az1"}
  subnet_2:
    cidr: 10.0.32.0/20
    az: ap-southeast-2b
    tags: {"Name":"coffeemate.network.subnet.admin.az2"}
  sg_1:
    name: coffeemate.network.sg.inout.common
    description: 'Common inbound / outbound rules that should apply to all resources'
  sg_2:
    name: coffeemate.network.sg.in.ssh-ext
    description: 'Inbound SSH traffic from anywhere. Should be applicable to management server only'
  sg_3:
    name: coffeemate.network.sg.out.all
    description: 'Outbound rule for a range of different protocols. For management and service now servers only'
  sg_common:
    cidr: 0.0.0.0/0
