---
#Common tasks across all servers. We scrapped wait to confirm SSH is up at this level because fact gathering always begins beforehand and script breaks. SSH check happens on final aws task
- name: 'Perform a ping test to ensure there is connectivity'
  ping:
- name: 'Update repository DB and upgrade existing packages. This step may take a while'
  sudo: true
  apt:
    update_cache: true
    upgrade: dist
- name: 'Install pciutils for administration'
  sudo: true
  apt:
    name: pciutils
    state: present
- name: 'Ensure GIT is installed'
  sudo: true
  apt:
    name: git
    state: present
- name: 'Ensure Ansible is installed'
  sudo: true
  apt:
    name: ansible
    state: present
#Not entirely happy with this configuration but was spending to much time on it. Improvements are welcomed
- name: 'Adjust Ansible configuration for use in AWS'
  sudo: true
  shell: cat /etc/ansible/ansible.cfg | grep "#CUSTOM SSH CONFIGURATIONS" | wc -l
  register: ansible_sshcfg_detect
- sudo: true
  shell: cat /etc/ansible/ansible.cfg | grep "#CUSTOM DEFAULT CONFIGURATIONS" | wc -l
  register: ansible_defcfg_detect
- sudo: true
  lineinfile:
    dest: '/etc/ansible/ansible.cfg'
    insertafter: '^\[ssh\_connection\]'
    line: '\n#CUSTOM SSH CONFIGURATIONS\n{{ ansible_cfg.control_path_desc }}\n{{ ansible_cfg.control_path_cfg }}\n'
  when: ansible_sshcfg_detect.stdout == "0"
- sudo: true
  lineinfile:
    dest: '/etc/ansible/ansible.cfg'
    insertafter: '^\[defaults\]'
    line: '\n#CUSTOM DEFAULT CONFIGURATIONS\n{{ ansible_cfg.host_key_checking_desc }}\n{{ ansible_cfg.host_key_checking_cfg }}'
  when: ansible_defcfg_detect.stdout == "0"
