---
#Common tasks across all servers. We scrapped wait to confirm SSH is up at this level because fact gathering always begins beforehand and script breaks. SSH check happens on final aws task
- name: 'Perform a ping test to ensure there is connectivity'
  ping:
- name: 'Update repository DB and upgrade existing packages. This step may take a while'
  sudo: true
  apt:
    update_cache: true
    upgrade: dist
- name: 'Ensure GIT is installed'
  sudo: true
  apt:
    name: git
    state: present
- name: 'Ensure Ansible is installed'
  sudo: true
  apt:
    name: ansible
    state: present
