---
#Perform a ping test to ensure there is connectivity. This is the only task required of the main.yml for common as we are really just ssh back into the same box
- name: 'Perform a ping test to ensure there is connectivity'
  ping:
