---
#Install and configure minimum software packages for each host
- name: 'Perform a ping test to ensure there is connectivity'
  ping:
- name: 'Update repository DB and upgrade existing packages. This step may take a while'
  sudo: true
  apt:
    update_cache: true
    upgrade: dist
- name: 'Install pciutils for administration'
  sudo: true
  apt:
    name: pciutils
    state: present
- name: 'Install curl'
  sudo: true
  apt:
    name: curl
    state: present
- name: 'Ensure GIT is installed and perform minimum configuration'
  sudo: true
  apt:
    name: git
    state: present
- name: 'Set system git username'
  sudo: true
  shell: 'git config --system user.name {{ git_cfg.system_user }}'
- name: 'Set system git email'
  sudo: true
  shell: 'git config --system user.email {{ git_cfg.system_email }}'
- name: 'Set global git username'
  shell: 'git config --global user.email {{ git_cfg.admin_user }}'
- name: 'Set global git email'
  shell: 'git config --global user.email {{ git_cfg.admin_email }}'
- name: 'Ensure Ansible is installed'
  sudo: true
  apt:
    name: ansible
    state: present
#Not entirely happy with this configuration but was spending to much time on it. Improvements are welcomed. May look at just setting a custom config on a per user basis
- name: 'Check and register if ansible control file path already modified'
  sudo: true
  shell: cat /etc/ansible/ansible.cfg | grep "#CUSTOM SSH CONFIGURATIONS" | wc -l
  register: ansible_sshcfg_detect
- name: 'Check and register if ansible configured to ignore known hosts'
  sudo: true
  shell: cat /etc/ansible/ansible.cfg | grep "#CUSTOM DEFAULT CONFIGURATIONS" | wc -l
  register: ansible_defcfg_detect
- name: 'Set control path'
  sudo: true
  lineinfile:
    dest: '/etc/ansible/ansible.cfg'
    insertafter: '^\[ssh\_connection\]'
    line: '\n#CUSTOM SSH CONFIGURATIONS\n{{ ansible_cfg.control_path_desc }}\n{{ ansible_cfg.control_path_cfg }}\n'
  when: ansible_sshcfg_detect.stdout == "0"
- name: 'Set ansible to ignore known hosts'
  sudo: true
  lineinfile:
    dest: '/etc/ansible/ansible.cfg'
    insertafter: '^\[defaults\]'
    line: '\n#CUSTOM DEFAULT CONFIGURATIONS\n{{ ansible_cfg.host_key_checking_desc }}\n{{ ansible_cfg.host_key_checking_cfg }}'
  when: ansible_defcfg_detect.stdout == "0"
