
---
#Install and configure minimum software packages for each host
- name: 'Perform a ping test to ensure there is connectivity'
  ping:
- name: 'Update repository DB and upgrade existing packages. This step may take a while'
  sudo: true
  apt:
    update_cache: true
    upgrade: dist
- name: 'Install pciutils for administration'
  sudo: true
  apt:
    name: pciutils
    state: present
- name: 'Install curl'
  sudo: true
  apt:
    name: curl
    state: present
- name: 'Install jshon'
  sudo: true
  apt:
    name: jshon
    state: present
- name: 'Install GIT'
  sudo: true
  apt:
    name: git
    state: present
- name: 'Set system GIT username'
  sudo: true
  shell: 'git config --system user.name {{ git_cfg.system_user }}'
- name: 'Set system GIT email'
  sudo: true
  shell: 'git config --system user.email {{ git_cfg.system_email }}'
- name: 'Set system wide config to use simple mode for push to remote repositories'
  sudo: true
  shell: 'git config --system push.default simple'
- name: 'Set global GIT username'
  shell: 'git config --global user.name {{ git_cfg.admin_user }}'
- name: 'Set global GIT email'
  shell: 'git config --global user.email {{ git_cfg.admin_email }}'
- name: 'Ansible Build Essentials'
  sudo: true
  apt:
    name: build-essential
    state: present
- name: 'Ansible Build Essentials'
  sudo: true
  apt:
    name: libssl-dev
    state: present
- name: 'Ansible Build Essentials'
  sudo: true
  apt:
    name: libffi-dev
    state: present
- name: 'Ansible Build Essentials'
  sudo: true
  apt:
    name: python-dev
    state: present
- name: 'Ansible Build Essentials'
  sudo: true
  apt:
    name: python-pip
    state: present
- name: 'Install Cryptography Module'
  sudo: true
  shell: sudo pip install cryptography --upgrade
- name: 'Install Ansible by PIP (this ensures we use the latest version on Debian)'
  sudo: true
  shell: sudo pip install ansible --upgrade
- name: 'Set Ansible Custom Configurations Required for Proper Operation in AWS'
  sudo: true
  template:
    backup: no
    force: yes
    mode: 0644
    dest: '/home/admin/.ansible.cfg'
    src: '.ansible.cfg.j2'
