---
#Update git repo and default packages. Install commonly required packages
- name: 'Perform a ping test to ensure there is connectivity'
  ping:
- name: 'Update repository DB and upgrade existing packages. This step may take a while'
  become: true
  become_method: sudo
  apt:
    update_cache: true
    upgrade: dist
- name: 'Install pciutils for administration'
  become: true
  become_method: sudo
  apt:
    name: pciutils
    state: present
- name: 'Install curl'
  become: true
  become_method: sudo
  apt:
    name: curl
    state: present
- name: 'Install jshon'
  become: true
  become_method: sudo
  apt:
    name: jshon
    state: present
