---
#Upload the private key files. The group_vars configuration ensure the correct private keys are uploaded
- name: 'Copy the private key as specified in the group vars to ssh directory'
  copy:
    src: "{{ ansible_ssh_private_key_upload }}"
    dest: /home/admin/.ssh/id_rsa
    mode: 0600
  when: ansible_ssh_private_key_upload is defined
- name: 'Copy the public key as specified in the group vars to ssh directory'
  copy: 
    src: "{{ ansible_ssh_public_key_upload }}"
    dest: /home/admin/.ssh/id_rsa.pub
    mode: 0644
  when: ansible_ssh_public_key_upload is defined
